export const CHARACTERS = {
  human: {
    id: 'human',
    name: 'Human',
    sprite: 'player',
    spriteSheet: 'player_sheet',
    animPrefix: 'player',
    hp: 100,
    speed: 90,
    startingWeapon: 'revolver',
    weaponUpgrade: 'revolverUp',
  },
  fencer: {
    id: 'fencer',
    name: 'Fencer',
    sprite: 'fencer',
    spriteSheet: 'fencer_sheet',
    animPrefix: 'fencer',
    hp: 80,
    speed: 102,
    startingWeapon: 'rapier',
    weaponUpgrade: 'rapierUp',
  },
  dealer: {
    id: 'dealer',
    name: 'Dealer',
    sprite: 'dealer',
    spriteSheet: 'dealer_sheet',
    animPrefix: 'dealer',
    hp: 90,
    speed: 96,
    startingWeapon: 'cardDeck',
    weaponUpgrade: 'cardDeckUp',
  },
  bloodMage: {
    id: 'bloodMage',
    name: 'Blood Mage',
    sprite: 'bloodMage',
    spriteSheet: 'bloodMage_sheet',
    animPrefix: 'bloodMage',
    hp: 50,
    speed: 88,
    startingWeapon: 'bloodOrb',
    weaponUpgrade: 'bloodOrbUp',
  },
  dronePilot: {
    id: 'dronePilot',
    name: 'Drone Pilot',
    sprite: 'dronePilot',
    spriteSheet: 'dronePilot_sheet',
    animPrefix: 'dronePilot',
    hp: 75,
    speed: 105,
    startingWeapon: 'laserDrones',
    weaponUpgrade: 'laserDronesUp',
  },
  snakeSwordsman: {
    id: 'snakeSwordsman',
    name: 'Snake Swordsman',
    sprite: 'snakeSwordsman',
    spriteSheet: 'snakeSwordsman_sheet',
    animPrefix: 'snakeSwordsman',
    hp: 90,
    speed: 94,
    startingWeapon: 'snakeSword',
    weaponUpgrade: 'snakeSwordUp',
  },
};
