// Cosmetic definitions — palette swaps (pass rewards) and visual additions (shop items)

export const COSMETICS = {
  // === Pass Reward Cosmetics (Palette Swaps) ===
  shadow_human: {
    id: 'shadow_human',
    name: 'Shadow Human',
    characterId: 'human',
    type: 'palette',
    source: 'pass',
    spriteKey: 'player_shadow',
    sheetKey: 'player_sheet_shadow',
    animPrefix: 'player_shadow',
    description: 'Dark purple recolor',
  },
  golden_fencer: {
    id: 'golden_fencer',
    name: 'Golden Fencer',
    characterId: 'fencer',
    type: 'palette',
    source: 'pass',
    spriteKey: 'fencer_golden',
    sheetKey: 'fencer_sheet_golden',
    animPrefix: 'fencer_golden',
    description: 'Gold recolor',
  },
  neon_dealer: {
    id: 'neon_dealer',
    name: 'Neon Dealer',
    characterId: 'dealer',
    type: 'palette',
    source: 'pass',
    spriteKey: 'dealer_neon',
    sheetKey: 'dealer_sheet_neon',
    animPrefix: 'dealer_neon',
    description: 'Cyan/pink neon recolor',
  },
  frost_bloodMage: {
    id: 'frost_bloodMage',
    name: 'Frost Blood Mage',
    characterId: 'bloodMage',
    type: 'palette',
    source: 'pass',
    spriteKey: 'bloodMage_frost',
    sheetKey: 'bloodMage_sheet_frost',
    animPrefix: 'bloodMage_frost',
    description: 'Ice blue recolor',
  },
  chrome_dronePilot: {
    id: 'chrome_dronePilot',
    name: 'Chrome Drone Pilot',
    characterId: 'dronePilot',
    type: 'palette',
    source: 'pass',
    spriteKey: 'dronePilot_chrome',
    sheetKey: 'dronePilot_sheet_chrome',
    animPrefix: 'dronePilot_chrome',
    description: 'Silver/white recolor',
  },

  // === Shop Cosmetics (Visual Additions) ===
  crimson_human: {
    id: 'crimson_human',
    name: 'Crimson Human',
    characterId: 'human',
    type: 'visual',
    source: 'shop',
    visualType: 'aura',
    color: 0xff4444,
    alpha: 0.35,
    radius: 12,
    description: 'Glowing red aura',
  },
  ice_fencer: {
    id: 'ice_fencer',
    name: 'Ice Fencer',
    characterId: 'fencer',
    type: 'visual',
    source: 'shop',
    visualType: 'trail',
    color: 0x88ccff,
    alpha: 0.5,
    description: 'Frost particle trail',
  },
  royal_dealer: {
    id: 'royal_dealer',
    name: 'Royal Dealer',
    characterId: 'dealer',
    type: 'visual',
    source: 'shop',
    visualType: 'crown',
    color: 0xffcc00,
    description: 'Golden crown accessory',
  },
  void_bloodMage: {
    id: 'void_bloodMage',
    name: 'Void Blood Mage',
    characterId: 'bloodMage',
    type: 'visual',
    source: 'shop',
    visualType: 'aura',
    color: 0x6622aa,
    alpha: 0.4,
    radius: 14,
    description: 'Dark swirling aura',
  },
  stealth_dronePilot: {
    id: 'stealth_dronePilot',
    name: 'Stealth Drone Pilot',
    characterId: 'dronePilot',
    type: 'visual',
    source: 'shop',
    visualType: 'aura',
    color: 0x22aa44,
    alpha: 0.3,
    radius: 10,
    description: 'Camo green glow',
  },
  jade_snakeSwordsman: {
    id: 'jade_snakeSwordsman',
    name: 'Jade Snake Swordsman',
    characterId: 'snakeSwordsman',
    type: 'visual',
    source: 'shop',
    visualType: 'aura',
    color: 0x44cc88,
    alpha: 0.35,
    radius: 12,
    description: 'Green jade glow',
  },
};

// Get all cosmetics for a specific character
export function getCosmeticsForCharacter(characterId) {
  return Object.values(COSMETICS).filter(c => c.characterId === characterId);
}
