export const ENEMIES = {
  greenSlime: {
    id: 'greenSlime',
    name: 'Green Slime',
    sprite: 'slime',
    baseHp: 10,
    speed: 32,
    damage: 9,
    xpValue: 5,
    colliderRadius: 8,
  },
  blueSlime: {
    id: 'blueSlime',
    name: 'Blue Slime',
    sprite: 'blueSlime',
    baseHp: 30,
    speed: 27,
    damage: 9,
    xpValue: 8,
    colliderRadius: 10,
    scale: 1.4,
    spawnAfter: 45,
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    sprite: 'skeleton',
    baseHp: 18,
    speed: 25,
    damage: 14,
    xpValue: 10,
    colliderRadius: 7,
    ranged: true,
    attackRange: 120,
    projectileSpeed: 70,
    fireRate: 2000,
    spawnAfter: 45,
    spawnWeight: 0.35,
  },
  scorpion: {
    id: 'scorpion',
    name: 'Scorpion',
    sprite: 'scorpion',
    baseHp: 12,
    speed: 38,
    damage: 10,
    xpValue: 6,
    colliderRadius: 7,
    movementPattern: 'skitter',
  },
  mummy: {
    id: 'mummy',
    name: 'Mummy',
    sprite: 'mummy',
    baseHp: 60,
    speed: 18,
    damage: 18,
    xpValue: 15,
    colliderRadius: 8,
    scale: 1.3,
    spawnAfter: 60,
    spawnWeight: 0.5,
    movementPattern: 'shuffle',
  },
  sandGolem: {
    id: 'sandGolem',
    name: 'Sand Golem',
    sprite: 'sandGolem',
    baseHp: 120,
    speed: 14,
    damage: 25,
    xpValue: 25,
    colliderRadius: 10,
    scale: 1.6,
    spawnAfter: 150,
    spawnWeight: 0.3,
    movementPattern: 'lumber',
  },
};
