export const ENEMIES = {
  greenSlime: {
    id: 'greenSlime',
    name: 'Green Slime',
    sprite: 'slime',
    baseHp: 10,
    speed: 32,
    damage: 9,
    xpValue: 5,
    colliderRadius: 8,
  },
  blueSlime: {
    id: 'blueSlime',
    name: 'Blue Slime',
    sprite: 'blueSlime',
    baseHp: 30,
    speed: 27,
    damage: 9,
    xpValue: 8,
    colliderRadius: 10,
    scale: 1.4,
    spawnAfter: 45,
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    sprite: 'skeleton',
    baseHp: 18,
    speed: 25,
    damage: 14,
    xpValue: 10,
    colliderRadius: 7,
    ranged: true,
    attackRange: 120,
    projectileSpeed: 70,
    fireRate: 2000,
    spawnAfter: 45,
    spawnWeight: 0.35,
  },
  scorpion: {
    id: 'scorpion',
    name: 'Scorpion',
    sprite: 'scorpion',
    baseHp: 12,
    speed: 38,
    damage: 10,
    xpValue: 6,
    colliderRadius: 7,
    movementPattern: 'skitter',
  },
  mummy: {
    id: 'mummy',
    name: 'Mummy',
    sprite: 'mummy',
    baseHp: 60,
    speed: 18,
    damage: 18,
    xpValue: 15,
    colliderRadius: 8,
    scale: 1.3,
    spawnAfter: 60,
    spawnWeight: 0.5,
    movementPattern: 'shuffle',
  },
  sandGolem: {
    id: 'sandGolem',
    name: 'Sand Golem',
    sprite: 'sandGolem',
    baseHp: 120,
    speed: 14,
    damage: 25,
    xpValue: 25,
    colliderRadius: 10,
    scale: 1.6,
    spawnAfter: 150,
    spawnWeight: 0.3,
    movementPattern: 'lumber',
  },
  // Ocean enemies
  jellyfish: {
    id: 'jellyfish',
    name: 'Jellyfish',
    sprite: 'jellyfish',
    baseHp: 15,
    speed: 28,
    damage: 12,
    xpValue: 7,
    colliderRadius: 7,
    movementPattern: 'drift',
  },
  anglerfish: {
    id: 'anglerfish',
    name: 'Anglerfish',
    sprite: 'anglerfish',
    baseHp: 25,
    speed: 22,
    damage: 16,
    xpValue: 12,
    colliderRadius: 8,
    ranged: true,
    attackRange: 140,
    projectileSpeed: 80,
    fireRate: 1800,
    spawnAfter: 45,
    spawnWeight: 0.4,
  },
  seaSerpent: {
    id: 'seaSerpent',
    name: 'Sea Serpent',
    sprite: 'seaSerpent',
    baseHp: 150,
    speed: 16,
    damage: 22,
    xpValue: 28,
    colliderRadius: 10,
    scale: 1.5,
    spawnAfter: 120,
    spawnWeight: 0.25,
    movementPattern: 'lumber',
  },
  // Moon enemies
  moonWorm: {
    id: 'moonWorm',
    name: 'Moon Worm',
    sprite: 'moonWorm',
    baseHp: 20,
    speed: 40,
    damage: 14,
    xpValue: 8,
    colliderRadius: 7,
    movementPattern: 'skitter',
  },
  voidPhantom: {
    id: 'voidPhantom',
    name: 'Void Phantom',
    sprite: 'voidPhantom',
    baseHp: 18,
    speed: 30,
    damage: 20,
    xpValue: 14,
    colliderRadius: 7,
    ranged: true,
    attackRange: 160,
    projectileSpeed: 90,
    fireRate: 1500,
    spawnAfter: 30,
    spawnWeight: 0.4,
  },
  sentinelDrone: {
    id: 'sentinelDrone',
    name: 'Sentinel Drone',
    sprite: 'sentinelDrone',
    baseHp: 180,
    speed: 12,
    damage: 30,
    xpValue: 35,
    colliderRadius: 10,
    scale: 1.7,
    spawnAfter: 90,
    spawnWeight: 0.2,
    movementPattern: 'lumber',
  },
};
