import { MAP_WIDTH, MAP_HEIGHT } from './GameConfig.js';

export const LEVELS = {
  plains: {
    id: 'plains',
    name: 'Plains',
    tileKey: 'grass',
    mapWidth: MAP_WIDTH,
    mapHeight: MAP_HEIGHT,
    obstacles: [{ type: 'tree', density: 0.00002 }],
    enemyTypes: ['greenSlime', 'blueSlime', 'skeleton'],
    spawnRate: { base: 1, scalePerMinute: 0.3 },
    duration: 300, // 5 minutes
    bossName: 'Slime King',
    bossSprite: 'bossSlimeKing',
    bossHp: 2000,
    bossDamage: 20,
    bossSpeed: 22,
  },
  desert: {
    id: 'desert',
    name: 'Desert',
    tileKey: 'sand',
    mapWidth: MAP_WIDTH,
    mapHeight: MAP_HEIGHT,
    obstacles: [{ type: 'cactus', density: 0.000015 }],
    enemyTypes: ['scorpion', 'mummy', 'sandGolem'],
    spawnRate: { base: 1, scalePerMinute: 0.3 },
    duration: 300,
    bossName: 'Mummy King',
    bossSprite: 'bossMummyKing',
    bossHp: 2500,
    bossDamage: 25,
    bossSpeed: 20,
  },
  dev: {
    id: 'dev',
    name: 'Dev',
    tileKey: 'grass',
    mapWidth: MAP_WIDTH,
    mapHeight: MAP_HEIGHT,
    obstacles: [],
    enemyTypes: ['greenSlime', 'blueSlime', 'skeleton', 'scorpion', 'mummy', 'sandGolem'],
    spawnRate: { base: 1, scalePerMinute: 0.3 },
    duration: 99999,
    isDev: true,
  },
};
