export const SHOP_ITEMS = [
  {
    id: 'xp_boost',
    name: 'XP Boost',
    description: '+50% post-game XP\n(1 game)',
    cost: 50,
    type: 'consumable',
    boostId: 'xp_boost',
    icon: 'icon_xpboost',
  },
  {
    id: 'crimson_human',
    name: 'Crimson Human',
    description: 'Glowing red aura\nfor Human',
    cost: 100,
    type: 'cosmetic',
    cosmeticId: 'crimson_human',
    characterId: 'human',
    icon: 'icon_cosmetic',
  },
  {
    id: 'ice_fencer',
    name: 'Ice Fencer',
    description: 'Frost particle trail\nfor Fencer',
    cost: 100,
    type: 'cosmetic',
    cosmeticId: 'ice_fencer',
    characterId: 'fencer',
    icon: 'icon_cosmetic',
  },
  {
    id: 'royal_dealer',
    name: 'Royal Dealer',
    description: 'Golden crown\nfor Dealer',
    cost: 100,
    type: 'cosmetic',
    cosmeticId: 'royal_dealer',
    characterId: 'dealer',
    icon: 'icon_cosmetic',
  },
  {
    id: 'void_bloodMage',
    name: 'Void Blood Mage',
    description: 'Dark swirling aura\nfor Blood Mage',
    cost: 100,
    type: 'cosmetic',
    cosmeticId: 'void_bloodMage',
    characterId: 'bloodMage',
    icon: 'icon_cosmetic',
  },
  {
    id: 'stealth_dronePilot',
    name: 'Stealth Drone Pilot',
    description: 'Camo green glow\nfor Drone Pilot',
    cost: 100,
    type: 'cosmetic',
    cosmeticId: 'stealth_dronePilot',
    characterId: 'dronePilot',
    icon: 'icon_cosmetic',
  },
  {
    id: 'jade_snakeSwordsman',
    name: 'Jade Snake Swordsman',
    description: 'Green jade glow\nfor Snake Swordsman',
    cost: 100,
    type: 'cosmetic',
    cosmeticId: 'jade_snakeSwordsman',
    characterId: 'snakeSwordsman',
    icon: 'icon_cosmetic',
  },
];
