export const UPGRADES = {
  damageAura: {
    id: 'damageAura',
    name: 'Damage Aura',
    description: 'Damages nearby enemies',
    icon: 'aura',
    maxLevel: 5,
    weaponClass: 'DamageAura',
    statsPerLevel: [
      { radius: 120, damage: 2, tickRate: 500 },
      { radius: 150, damage: 3, tickRate: 450 },
      { radius: 180, damage: 4, tickRate: 400 },
      { radius: 210, damage: 5, tickRate: 350 },
      { radius: 240, damage: 7, tickRate: 300 },
    ],
  },
  unicornRider: {
    id: 'unicornRider',
    name: 'Unicorn Rider',
    description: 'A man on a unicorn charges across the screen',
    icon: 'unicorn',
    maxLevel: 5,
    weaponClass: 'UnicornRider',
    statsPerLevel: [
      { damage: 50, cooldown: 8000, speed: 300 },
      { damage: 65, cooldown: 7000, speed: 325 },
      { damage: 80, cooldown: 6000, speed: 350 },
      { damage: 100, cooldown: 5000, speed: 375 },
      { damage: 130, cooldown: 4000, speed: 400 },
    ],
  },
  spearRain: {
    id: 'spearRain',
    name: 'Spear Rain',
    description: 'Rains spears from the sky',
    icon: 'spear',
    maxLevel: 5,
    weaponClass: 'SpearRain',
    statsPerLevel: [
      { spearCount: 2, damage: 15, cooldown: 5000 },
      { spearCount: 4, damage: 18, cooldown: 4500 },
      { spearCount: 6, damage: 22, cooldown: 4000 },
      { spearCount: 8, damage: 26, cooldown: 3500 },
      { spearCount: 10, damage: 30, cooldown: 3000 },
    ],
  },
  piercingDart: {
    id: 'piercingDart',
    name: 'Piercing Dart',
    description: 'Auto-aiming dart that pierces enemies',
    icon: 'dart',
    maxLevel: 5,
    weaponClass: 'PiercingDart',
    statsPerLevel: [
      { damage: 5, fireRate: 1500, speed: 250 },
      { damage: 7, fireRate: 1300, speed: 275 },
      { damage: 9, fireRate: 1100, speed: 300 },
      { damage: 12, fireRate: 900, speed: 325 },
      { damage: 16, fireRate: 700, speed: 350 },
    ],
  },
  flameTrail: {
    id: 'flameTrail',
    name: 'Flame Trail',
    description: 'Leaves spreading fire behind you',
    icon: 'flame',
    maxLevel: 5,
    weaponClass: 'FlameTrail',
    statsPerLevel: [
      { dropRate: 400, damage: 3, duration: 3000, spreadChance: 0.1 },
      { dropRate: 350, damage: 4, duration: 3500, spreadChance: 0.15 },
      { dropRate: 300, damage: 5, duration: 4000, spreadChance: 0.2 },
      { dropRate: 250, damage: 7, duration: 4500, spreadChance: 0.25 },
      { dropRate: 200, damage: 9, duration: 5000, spreadChance: 0.3 },
    ],
  },
  tornado: {
    id: 'tornado',
    name: 'Tornado',
    description: 'Summons a wandering tornado',
    icon: 'tornado',
    maxLevel: 5,
    weaponClass: 'Tornado',
    statsPerLevel: [
      { damage: 4, speed: 80, duration: 5000, cooldown: 8000 },
      { damage: 6, speed: 90, duration: 5500, cooldown: 7000 },
      { damage: 8, speed: 100, duration: 6000, cooldown: 6000 },
      { damage: 10, speed: 110, duration: 7000, cooldown: 5000 },
      { damage: 13, speed: 120, duration: 8000, cooldown: 4000 },
    ],
  },
};
