export const UPGRADES = {
  damageAura: {
    id: 'damageAura',
    name: 'Damage Aura',
    description: 'Damages nearby enemies',
    icon: 'aura',
    maxLevel: 5,
    weaponClass: 'DamageAura',
    statsPerLevel: [
      { radius: 55, damage: 3, tickRate: 450 },
      { radius: 70, damage: 5, tickRate: 400 },
      { radius: 85, damage: 7, tickRate: 350 },
      { radius: 100, damage: 9, tickRate: 300 },
      { radius: 120, damage: 12, tickRate: 250 },
    ],
  },
  unicornRider: {
    id: 'unicornRider',
    name: 'Unicorn Rider',
    description: 'A man on a unicorn charges across the screen',
    icon: 'unicorn',
    maxLevel: 5,
    weaponClass: 'UnicornRider',
    statsPerLevel: [
      { damage: 50, cooldown: 8000, speed: 300 },
      { damage: 65, cooldown: 6000, speed: 325 },
      { damage: 80, cooldown: 4500, speed: 350 },
      { damage: 100, cooldown: 3000, speed: 375 },
      { damage: 130, cooldown: 2000, speed: 400 },
    ],
  },
  spearRain: {
    id: 'spearRain',
    name: 'Spear Rain',
    description: 'Rains spears from the sky',
    icon: 'spear',
    maxLevel: 5,
    weaponClass: 'SpearRain',
    statsPerLevel: [
      { spearCount: 3, damage: 15, cooldown: 4000 },
      { spearCount: 5, damage: 18, cooldown: 3500 },
      { spearCount: 7, damage: 22, cooldown: 3000 },
      { spearCount: 9, damage: 26, cooldown: 2500 },
      { spearCount: 12, damage: 30, cooldown: 2000 },
    ],
  },
  piercingDart: {
    id: 'piercingDart',
    name: 'Piercing Dart',
    description: 'Auto-aiming dart that pierces enemies',
    icon: 'dart',
    maxLevel: 5,
    weaponClass: 'PiercingDart',
    statsPerLevel: [
      { damage: 5, fireRate: 1500, speed: 220, range: 150 },
      { damage: 7, fireRate: 1300, speed: 230, range: 160 },
      { damage: 9, fireRate: 1100, speed: 240, range: 170 },
      { damage: 12, fireRate: 900, speed: 250, range: 180 },
      { damage: 16, fireRate: 700, speed: 260, range: 200 },
    ],
  },
  flameTrail: {
    id: 'flameTrail',
    name: 'Flame Trail',
    description: 'Leaves spreading fire behind you',
    icon: 'flame',
    maxLevel: 5,
    weaponClass: 'FlameTrail',
    statsPerLevel: [
      { dropRate: 400, damage: 3, duration: 3000, spreadChance: 0.1 },
      { dropRate: 350, damage: 4, duration: 3500, spreadChance: 0.15 },
      { dropRate: 300, damage: 5, duration: 4000, spreadChance: 0.2 },
      { dropRate: 250, damage: 7, duration: 4500, spreadChance: 0.25 },
      { dropRate: 200, damage: 9, duration: 5000, spreadChance: 0.3 },
    ],
  },
  tornado: {
    id: 'tornado',
    name: 'Tornado',
    description: 'Summons a permanent wandering tornado',
    icon: 'tornado',
    maxLevel: 5,
    weaponClass: 'Tornado',
    statsPerLevel: [
      { damage: 8, speed: 100, count: 1 },
      { damage: 12, speed: 115, count: 2 },
      { damage: 16, speed: 130, count: 3 },
      { damage: 22, speed: 145, count: 4 },
      { damage: 30, speed: 160, count: 5 },
    ],
  },
  revolverUp: {
    id: 'revolverUp',
    name: 'Revolver',
    description: 'Upgrades your revolver',
    icon: 'bullet',
    maxLevel: 5,
    weaponClass: 'Revolver',
    characterOnly: 'human',
    statsPerLevel: [
      { fireRate: 450, damage: 9, bulletSpeed: 260, range: 180 },
      { fireRate: 350, damage: 13, bulletSpeed: 270, range: 210 },
      { fireRate: 270, damage: 18, bulletSpeed: 280, range: 240 },
      { fireRate: 200, damage: 24, bulletSpeed: 290, range: 270 },
      { fireRate: 150, damage: 32, bulletSpeed: 300, range: 300 },
    ],
  },
  rapierUp: {
    id: 'rapierUp',
    name: 'Rapier',
    description: 'Upgrades your rapier',
    icon: 'rapier',
    maxLevel: 5,
    weaponClass: 'Rapier',
    characterOnly: 'fencer',
    statsPerLevel: [
      { fireRate: 800, damage: 20, range: 270 },
      { fireRate: 750, damage: 28, range: 285 },
      { fireRate: 700, damage: 36, range: 300 },
      { fireRate: 650, damage: 45, range: 315 },
      { fireRate: 600, damage: 55, range: 330 },
    ],
  },
  cardDeckUp: {
    id: 'cardDeckUp',
    name: 'Card Deck',
    description: 'Upgrades your card throws',
    icon: 'card_spade',
    maxLevel: 5,
    weaponClass: 'CardDeck',
    characterOnly: 'dealer',
    statsPerLevel: [
      { fireRate: 700, damage: 8, speed: 230, range: 150, diamondBonusXP: 2 },
      { fireRate: 620, damage: 11, speed: 240, range: 160, diamondBonusXP: 2 },
      { fireRate: 550, damage: 15, speed: 250, range: 170, diamondBonusXP: 3 },
      { fireRate: 480, damage: 19, speed: 260, range: 180, diamondBonusXP: 3 },
      { fireRate: 400, damage: 24, speed: 270, range: 200, diamondBonusXP: 4 },
    ],
  },
  bloodOrbUp: {
    id: 'bloodOrbUp',
    name: 'Blood Orb',
    description: 'Upgrades your blood orb',
    icon: 'bloodOrb',
    maxLevel: 5,
    weaponClass: 'BloodOrb',
    characterOnly: 'bloodMage',
    statsPerLevel: [
      { fireRate: 820, damage: 10, bulletSpeed: 190, range: 150, lifeStealPercent: 0.18, killHealPercent: 0.07 },
      { fireRate: 750, damage: 13, bulletSpeed: 200, range: 160, lifeStealPercent: 0.21, killHealPercent: 0.09 },
      { fireRate: 680, damage: 17, bulletSpeed: 210, range: 170, lifeStealPercent: 0.25, killHealPercent: 0.12 },
      { fireRate: 600, damage: 22, bulletSpeed: 220, range: 180, lifeStealPercent: 0.30, killHealPercent: 0.15 },
      { fireRate: 520, damage: 28, bulletSpeed: 230, range: 200, lifeStealPercent: 0.35, killHealPercent: 0.18 },
    ],
  },
  magnetRange: {
    id: 'magnetRange',
    name: 'Magnet',
    description: 'Increases XP pickup range',
    icon: 'xpGem',
    maxLevel: 5,
    isPassive: true,
    statsPerLevel: [
      { magnetRadius: 50 },
      { magnetRadius: 75 },
      { magnetRadius: 105 },
      { magnetRadius: 140 },
      { magnetRadius: 180 },
    ],
  },
  speedBoost: {
    id: 'speedBoost',
    name: 'Swift Boots',
    description: 'Increases movement speed',
    icon: 'boot',
    maxLevel: 5,
    isPassive: true,
    statsPerLevel: [
      { speedBonus: 12 },
      { speedBonus: 26 },
      { speedBonus: 42 },
      { speedBonus: 60 },
      { speedBonus: 80 },
    ],
  },
  laserDronesUp: {
    id: 'laserDronesUp',
    name: 'Laser Drones',
    description: 'Upgrades your laser drones',
    icon: 'drone',
    maxLevel: 5,
    weaponClass: 'LaserDrones',
    characterOnly: 'dronePilot',
    statsPerLevel: [
      { damage: 25, fireRate: 1800, range: 180, pierceCount: 1 },
      { damage: 32, fireRate: 1650, range: 190, pierceCount: 2 },
      { damage: 40, fireRate: 1500, range: 200, pierceCount: 3 },
      { damage: 50, fireRate: 1350, range: 210, pierceCount: 4 },
      { damage: 62, fireRate: 1200, range: 220, pierceCount: 5 },
    ],
  },
  snakeSwordUp: {
    id: 'snakeSwordUp',
    name: 'Snake Sword',
    description: 'Upgrades your snake sword',
    icon: 'snakeSword',
    maxLevel: 5,
    weaponClass: 'SnakeSword',
    characterOnly: 'snakeSwordsman',
    statsPerLevel: [
      { slashRate: 600, slashDamage: 10, poisonRate: 900, poisonDamage: 5, poisonSpeed: 180, range: 160 },
      { slashRate: 550, slashDamage: 13, poisonRate: 820, poisonDamage: 7, poisonSpeed: 190, range: 170 },
      { slashRate: 500, slashDamage: 16, poisonRate: 740, poisonDamage: 9, poisonSpeed: 200, range: 180 },
      { slashRate: 450, slashDamage: 20, poisonRate: 660, poisonDamage: 11, poisonSpeed: 210, range: 190 },
      { slashRate: 400, slashDamage: 24, poisonRate: 580, poisonDamage: 13, poisonSpeed: 220, range: 200 },
    ],
  },
  xpBoost: {
    id: 'xpBoost',
    name: 'XP Boost',
    description: 'Increases XP gained',
    icon: 'xpGem',
    maxLevel: 5,
    isPassive: true,
    statsPerLevel: [
      { xpMultiplier: 1.1 },
      { xpMultiplier: 1.2 },
      { xpMultiplier: 1.3 },
      { xpMultiplier: 1.4 },
      { xpMultiplier: 1.5 },
    ],
  },
  bugs: {
    id: 'bugs',
    name: 'Bugs',
    description: 'Swarms of bugs chase down enemies',
    icon: 'bug',
    maxLevel: 5,
    weaponClass: 'BugSwarm',
    statsPerLevel: [
      { swarmCount: 1, bugsPerSwarm: 4, damage: 2, speed: 170 },
      { swarmCount: 2, bugsPerSwarm: 5, damage: 2.5, speed: 185 },
      { swarmCount: 3, bugsPerSwarm: 5, damage: 3, speed: 200 },
      { swarmCount: 4, bugsPerSwarm: 6, damage: 3.5, speed: 215 },
      { swarmCount: 5, bugsPerSwarm: 6, damage: 4, speed: 230 },
    ],
  },
};
